bindings:
  - name: kubemq-query-aws-s3
    source:
      kind: source.query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-aws-s3-connector"
        auth_token: ""
        channel: "query.aws.s3"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.aws.s3
      name: target-aws-s3
      properties:
        aws_key: "id"
        aws_secret_key: 'json'
        region:  "region"
        downloader:  "true"
        uploader:  "true"