bindings:
  - name: nats
    source:
      kind: kubemq.events
      properties:
        address: localhost:50000
        channel: event.messaging.nats
    target:
      kind: messaging.nats
      properties:
        cert_file: |-
          -----BEGIN CERTIFICATE-----
          -----END CERTIFICATE-----
        cert_key: |-
          -----BEGIN PRIVATE KEY-----
          jrwkrWynmfwXr1ctWeb7O4W9Ng==
          -----END PRIVATE KEY-----
        dynamic_mapping: "false"
        url: nats://localhost:4222
    properties: {}
