bindings:
  - name: kubemq-query-azuresql
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-azuresql-connector"
        auth_token: ""
        channel: "query.azuresql"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: azure.stores.azuresql
      name: azure-stores-azuresql
      properties:
        connection: 'server=server.net;user id=test;password=test;port=1433;database=initial_db;'
        max_idle_connections: "10"
        max_open_connections: "100"
        connection_max_lifetime_seconds: "3600"
