apiPort: 8081
bindings:
  - name: bigquery
    source:
      kind: kubemq.q
      properties:
        address: localhost:50000
        channel: query.bigquery
    target:
      kind: gcp.bigquery
      properties:
        credentials: |-

        project_id: kubemq
    properties:
      log_level: debug
