bindings:
- name: hazelcast
  source:
    kind: kubemq.query
    properties:
      address: localhost:50000
      channel: query.hazelcast
  target:
    kind: cache.hazelcast
    properties:
      address: localhost:5701
      server name: test
  properties: {}
