bindings:
- name: percona
  source:
    kind: kubemq.query
    properties:
      address: localhost:50000
      channel: query.percona
  target:
    kind: stores.percona
    properties:
      connection: root:root@(localhost:3306)/percona?charset=utf8&parseTime=True&loc=Local
  properties: {}
