bindings:
  - name: kubemq-query-mssql
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-mssql-connector"
        auth_token: ""
        channel: "query.mssql"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:stores.mssql
      name: target-mssql
      properties:
        connection: "sqlserver://sa:n8x2Nz!f@localhost:1433?database=master"
        max_idle_connections: "10"
        max_open_connections: "100"
        connection_max_lifetime_seconds: "3600"
    properties:
      log_level: "error"
