bindings:
  - name: kubemq-query-aws-cloudwatch-events
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-aws-cloudwatch-events"
        auth_token: ""
        channel: "query.aws.cloudwatch.events"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:aws.cloudwatch.events
      name: target-aws-cloudwatch-events
      properties:
        aws_key: "id"
        aws_secret_key: 'json'
        region:  "region"
        token: ""
