bindings:
  - name: kubemq-query-aws-cloudwatch-metrics
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-aws-cloudwatch-metrics"
        auth_token: ""
        channel: "query.aws.cloudwatch.metrics"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:aws.cloudwatch.metrics
      name: target-aws-cloudwatch-metrics
      properties:
        aws_key: "id"
        aws_secret_key: 'json'
        region:  "region"
        token: ""
