bindings:
  - name: kubemq-query-aws-postgres
    source:
      kind: source.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-aws-postgres-connector"
        auth_token: ""
        channel: "query.aws.rds.postgres"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.aws.rds.postgres
      name: target-aws-rds-postgres
      properties:
        db_user: "test"
        db_name: "test"
        end_point: "my-end-point"
        aws_key: "id"
        aws_secret_key: 'json'
        region:  "region"
        max_idle_connections: "10"
        max_open_connections: "100"
        connection_max_lifetime_seconds: "3600"
