 bindings:
  - name: kubemq-query-gcp-redis
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-gcp-redis-connector"
        auth_token: ""
        channel: "query.redis"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:gcp.cache.redis
      name: target-gcp-redis
      properties:
        url: "redis://localhost:6379"
