bindings:
  - name: kubemq-query-aws-elasticsearch
    source:
      kind: source.query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-aws-elasticsearch-connector"
        auth_token: ""
        channel: "query.aws.elasticsearch"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.aws.elasticsearch
      name: target-aws-elasticsearch
      properties:
        aws_key: "id"
        aws_secret_key: 'json'