bindings:
  - name: kubemq-query-aws-elasticsearch
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-aws-elasticsearch-connector"
        auth_token: ""
        channel: "query.aws.elasticsearch"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: aws.elasticsearch
      name: aws-elasticsearch
      properties:
        aws_key: "id"
        aws_secret_key: 'json'
        token: ""
