bindings:
  - name: kubemq-query-activemq
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-activemq-connector"
        auth_token: ""
        channel: "query.activemq"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:messaging.activemq
      name: target-activemq
      properties:
        host: "localhost:61613"
        username: "admin"
        password: "admin"
    properties:
      log_level: "error"
