bindings:
  - name: kubemq-query-kafka
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-gcpfirebase-connector"
        auth_token: ""
        channel: "query.gcp.firebase"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:gcp.firebase
      name: target-gcp-firebase
      properties:
        project_id: "pubsubdemo-281010"
        credentials: '{
          "type": "service_account",
          "project_id": "pubsubdemo-281010",
          "private_key_id": ""}'
        messaging_client: "true"
        defaultmsg: '{"Topic":"Multi"}'
      
