bindings:
  - name: aerospike
    source:
      kind: kubemq.query
      properties:
        address: localhost:50000
        channel: query.aerospike
    target:
      kind: stores.aerospike
      properties:
        host: localhost
        port: "3000"
    properties: {}
