bindings:
  - name: kubemq-query-aws-redshift-service
    source:
      kind: source.query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-aws-redshift-connector"
        auth_token: ""
        channel: "query.aws.redshift.service"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.aws.redshift.service
      name: target-aws-redshift-service
      properties:
        aws_key: "id"
        aws_secret_key: 'json'
        region:  "region"