bindings:
  - name: kubemq-query-http
    source:
      kind: source.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-http-connector"
        auth_token: ""
        channel: "query.http"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.http
      name: target-http
      properties:
        auth_type: "no-auth"
        default_headers: '{"Content-Type":"application/json"}'
    properties:
      log_level: "error"
