bindings:
  - name: kubemq-query-azure-mysql
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-azure-mysql-connector"
        auth_token: ""
        channel: "query.azure.mysql"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: azure.stores.mysql
      name: azure-stores-mysql
      properties:
        connection: "username@host:password@tcp(endpoint:3306)/dbname?allowNativePasswords=true"
        max_idle_connections: "10"
        max_open_connections: "100"
        connection_max_lifetime_seconds: "3600"
