bindings:
  - name: kubemq-query-gcp-pubsub
    source:
      kind: source.query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-gcp-pubsub-connector"
        auth_token: ""
        channel: "query.gcp.pubsub"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.gcp.pubsub
      name: target-gcp-pubsub
      properties:
        project_id: "projectID"
        retries:    "0"
        credentials: 'json'
