bindings:
  - name: rabbitmq
    source:
      kind: kubemq.query
      properties:
        address: localhost:50000
        auth_token: ""
        channel: messaging.rabbitmq
        client_id: test
    target:
      kind: messaging.rabbitmq
      properties:
        url: amqp://guest:guest@localhost:5672/
    properties: {}
