bindings:
  - name: kubemq-query-gcp-bigtable
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-gcp-bigtable-connector"
        auth_token: ""
        channel: "query.gcp.bigtable"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:gcp.bigtable
      name: gcp-bigtable
      properties:
        project_id: "id"
        credentials: 'json'
        instance: "instance"
