bindings:
  - name: ibmmq
    source:
      kind: kubemq.query
      properties:
        address: localhost:50000
        channel: query.ibm.ibmmq
    target:
      kind: ibm.ibmmq
      properties:
        channel_name: DEV.APP.SVRCONN
        host_name: localhost
        password: passw0rd
        port_number: "1414"
        queue_manager_name: QM1
        queue_name: admin
        tls_client_auth: NONE
        transport_type: "0"
        ttl: "1000000"
        username: app
    properties: {}
